apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: odh-dashboard
  app.kubernetes.io/part-of: odh-dashboard
resources:
  - ../apps
  - ../modelserving
  - role.yaml
  - cluster-role.yaml
  - service-account.yaml
  - role-binding.yaml
  - cluster-role-binding.yaml
  - auth-delegator.clusterrolebinding.yaml
  - cluster-monitoring-role-binding.yaml
  - deployment.yaml
  - exporter.yaml
  - routes.yaml
  - service.yaml
  - oauth.secret.yaml
  - fetch-builds-and-images.rbac.yaml
  - image-puller.clusterrolebinding.yaml
  - model-serving-role.yaml
  - model-serving-role-binding.yaml
images:
- name: odh-dashboard
  newName: ghcr.io/maia-iyer/mcad-dashboard
  newTag: 49fd8802d8a13802907b6866b6b98b8d8da95547
- name: oauth-proxy
  newName: registry.redhat.io/openshift4/ose-oauth-proxy
  digest: sha256:ab112105ac37352a2a4916a39d6736f5db6ab4c29bad4467de8d613e80e9bb33
- name: mcad-exporter
  newName: ghcr.io/maia-iyer/mcad-exporter
  newTag: 49fd8802d8a13802907b6866b6b98b8d8da95547
